export declare enum CypherKeyWords {
    START = "START ",
    MATCH = "MATCH ",
    OPTIONAL_MATCH = "OPTIONAL MATCH ",
    MERGE = "MERGE ",
    CREATE = "CREATE ",
    DELETE = "DELETE ",
    WHERE = "WHERE ",
    WITH = "WITH ",
    SET = "SET ",
    ORDER_BY = "ORDER BY ",
    SKIP = "SKIP ",
    LIMIT = "LIMIT ",
    RETURN = "RETURN ",
    DISTINCT = "DISTINCT ",
    CREATE_INDEX_ON = "CREATE INDEX ON ",
    USING_INDEX_ON = "USING INDEX ON ",
    DROP_INDEX_ON = "DROP INDEX ON ",
}
